/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.ImageIcon;

/**
 *
 * @author MSI
 */
public class Menu1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    public Menu1() {
    initComponents();
    
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PnlBanner = new javax.swing.JPanel();
        pnlManager = new javax.swing.JLabel();
        btnDrinkManager = new javax.swing.JButton();
        btnCategoryManager = new javax.swing.JButton();
        btnCardManager = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        pnlManager1 = new javax.swing.JLabel();
        btnDrinkManager1 = new javax.swing.JButton();
        btnDrinkManager2 = new javax.swing.JButton();
        btnDrinkManager3 = new javax.swing.JButton();
        btnDrinkManager4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\CaoDangFPT\\DuAn1\\DuAn1_N1\\src\\images\\Screenshot 2025-07-11 225902.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlBanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PnlBanner.add(pnlManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -20, -1, 20));

        btnDrinkManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDrinkManager.setText("Đăng ký / Đăng nhập");
        btnDrinkManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnDrinkManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 50));

        btnCategoryManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategoryManager.setText("Đánh giá món ăn");
        btnCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnCategoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, 50));

        btnCardManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCardManager.setText("Quản lý dữ liệu");
        btnCardManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnCardManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 170, 50));

        btnBillManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBillManager.setText("Lịch sử mua hàng");
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnBillManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 170, 50));

        btnUserManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserManager.setText("NGƯỜI SỬ DỤNG");
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 160, 50));

        btnRevenueManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRevenueManager.setText("DOANH THU");
        btnRevenueManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueManagerActionPerformed(evt);
            }
        });
        PnlBanner.add(btnRevenueManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 170, 50));
        PnlBanner.add(pnlManager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -100, -1, -1));

        btnDrinkManager1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDrinkManager1.setText("Theo dõi đơn hàng");
        btnDrinkManager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManager1ActionPerformed(evt);
            }
        });
        PnlBanner.add(btnDrinkManager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 170, 50));

        btnDrinkManager2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDrinkManager2.setText("Tìm kiếm món ăn");
        btnDrinkManager2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManager2ActionPerformed(evt);
            }
        });
        PnlBanner.add(btnDrinkManager2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, 50));

        btnDrinkManager3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDrinkManager3.setText("Giỏ hàng");
        btnDrinkManager3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManager3ActionPerformed(evt);
            }
        });
        PnlBanner.add(btnDrinkManager3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 160, 50));

        btnDrinkManager4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDrinkManager4.setText("Xem thực đơn");
        btnDrinkManager4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkManager4ActionPerformed(evt);
            }
        });
        PnlBanner.add(btnDrinkManager4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\CaoDangFPT\\DuAn1\\DuAn1_N1\\src\\images\\Screenshot 2025-07-11 225902.png")); // NOI18N
        PnlBanner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 340));

        getContentPane().add(PnlBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrinkManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManagerActionPerformed
        this.showDrinkManagerJDialog(this);
    }//GEN-LAST:event_btnDrinkManagerActionPerformed

    private void btnCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryManagerActionPerformed
        this.showCategoryManagerJDialog(this);
    }//GEN-LAST:event_btnCategoryManagerActionPerformed

    private void btnCardManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardManagerActionPerformed
        this.showCardManagerJDialog(this);
    }//GEN-LAST:event_btnCardManagerActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        this.showBillManagerJDialog(this);
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        this.showUserManagerJDialog(this);
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnRevenueManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueManagerActionPerformed
        this.showRevenueManagerJDialog(this);
    }//GEN-LAST:event_btnRevenueManagerActionPerformed

    private void btnDrinkManager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManager1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkManager1ActionPerformed

    private void btnDrinkManager2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManager2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkManager2ActionPerformed

    private void btnDrinkManager3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManager3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkManager3ActionPerformed

    private void btnDrinkManager4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkManager4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkManager4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlBanner;
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnCardManager;
    private javax.swing.JButton btnCategoryManager;
    private javax.swing.JButton btnDrinkManager;
    private javax.swing.JButton btnDrinkManager1;
    private javax.swing.JButton btnDrinkManager2;
    private javax.swing.JButton btnDrinkManager3;
    private javax.swing.JButton btnDrinkManager4;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pnlManager;
    private javax.swing.JLabel pnlManager1;
    // End of variables declaration//GEN-END:variables
}
